/* 
 * RoverOnMarsApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = RoverOnMarsApi.Swagger.Client.SwaggerDateConverter;

namespace RoverOnMarsApi.Swagger.Model
{
    /// <summary>
    /// Defines DirectionEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DirectionEnum
    {
        /// <summary>
        /// Enum Nord for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        Nord,
        /// <summary>
        /// Enum Sud for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        Sud,
        /// <summary>
        /// Enum Est for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        Est,
        /// <summary>
        /// Enum West for value: 3
        /// </summary>
        [EnumMember(Value = "3")]
        West
    }
}
